import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LayouNav from "@/page_components/Navigation/LayoutNav";
import styles from "./page.module.css";
import WrapperProvider from "@/context/WrapperProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={styles.body}>
        <WrapperProvider>
          <LayouNav />
          {children}
        </WrapperProvider>
      </body>
    </html>
  );
}
